[package]
name = "xtask"
version = "0.8.3"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
color-eyre = "0.6.5"
cargo_metadata = "0.21.0"
duct = "1.1.0"
walkdir = "2.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
toml = "0.9.5"
anyhow = "1.0.98"
indicatif = "0.18.0"
console = "0.16.0"
chrono = { version = "0.4.41", features = ["serde"] }
tree-sitter-perl = { workspace = true, features = ["rust-scanner"] }
perl-parser = { workspace = true }
tree-sitter = { workspace = true }
regex = "1.11.1"
serde_yaml = "0.9"

[dev-dependencies]
tempfile = "3.8"
