[package]
name = "perl-pragma"
version = "0.9.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
perl-ast = { workspace = true }

[lints]
workspace = true
