[package]
name = "perl-builtins"
version = "0.9.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
phf = { version = "0.13.1", features = ["macros"] }

[lints]
workspace = true
