[package]
name = "perl-edit"
version = "0.9.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
perl-position-tracking = { workspace = true }

[dev-dependencies]
perl-tdd-support = { workspace = true }

[lints]
workspace = true
